language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:paparazzi-uav/ppa -y
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -q
install:
  - sudo apt-get install paparazzi-dev paparazzi-jsbsim gcc-arm-none-eabi libipc-run-perl
before_script: cd conf && ln -s conf_tests.xml conf.xml && cd ..
script:
  - make
  - make -C tests/math test
  - PAPARAZZI_SRC=$PWD PAPARAZZI_HOME=$PWD J=AUTO prove tests/examples/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4187f8dda7a22a92b749
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
